'use client';
import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {browserDatabase} from '@/lib/supabase/client';
import MathBridge from './mathbridge';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function AuthGate(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'signup'|'reset'|'update'>('login'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true;try{const db=browserDatabase();db.auth.getSession().then(({data,error})=>{if(live){setSession(data.session);setLoading(false);if(error)setError(error.message)}});const {data}=db.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setMode('update')});return()=>{live=false;data.subscription.unsubscribe()}}catch(e){setLoading(false);setError(e instanceof Error?e.message:'Could not connect')}} ,[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const db=browserDatabase();const credentials={email:email.trim().toLowerCase(),password};
  if(mode==='login'){const r=await db.auth.signInWithPassword(credentials);if(r.error)throw r.error;setSession(r.data.session)}
  else if(mode==='signup'){const r=await db.auth.signUp({...credentials,options:{emailRedirectTo:window.location.origin}});if(r.error)throw r.error;if(r.data.session)setSession(r.data.session);else setMessage('Check your email to confirm your account, then return here to sign in.');}
  else if(mode==='reset'){const r=await db.auth.resetPasswordForEmail(credentials.email,{redirectTo:window.location.origin});if(r.error)throw r.error;setMessage('If this account exists, a password reset link will arrive by email.');}
  else{const r=await db.auth.updateUser({password});if(r.error)throw r.error;setPassword('');setMode('login');setMessage('Your password has been updated.');}
 }catch(e){setError(e instanceof Error?e.message:'Could not sign in. Please try again.')}finally{setBusy(false)}}
 async function signOut(){setError('');const {error}=await browserDatabase().auth.signOut();if(error)setError(error.message);else{setSession(null);setPassword('')}}
 if(loading)return <div className="loading">Opening your learning space…</div>;
 if(session&&mode!=='update')return <><div className="account-bar"><span>Private learning space</span><Button variant="ghost" onClick={signOut}>Sign out</Button>{error&&<span role="alert">{error}</span>}</div><MathBridge key={session.user.id}/></>;
 return <main className="auth-page"><div className="auth-story"><a href="/" className="brand">math<span className="brand-light">bridge</span></a><p className="eyebrow">ALGEBRA FOUNDATIONS</p><h1>A little progress.<br/>A stronger foundation.</h1><p>Understand the idea, practise at your pace, and return to a learning path that remembers your work.</p><div className="auth-facts"><span>16 skills</span><span>144 practice questions</span><span>English + Urdu key ideas</span></div></div><section className="auth-card"><p className="eyebrow">PRIVATE PILOT</p><h2>{mode==='signup'?'Create your learning account':mode==='reset'?'Reset your password':mode==='update'?'Choose a new password':'Welcome to your learning space'}</h2><p>Use your invited email address. Your learning progress stays private to your account.</p><form onSubmit={submit}>{mode!=='update'&&<><label htmlFor="email">Email address</label><Input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></>}{mode!=='reset'&&<><label htmlFor="password">Password</label><Input id="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} required value={password} onChange={e=>setPassword(e.target.value)}/>{mode!=='login'&&<small>Use at least 12 characters.</small>}</>}{error&&<p className="error-text" role="alert">{error}</p>}{message&&<p className="auth-message" role="status">{message}</p>}<Button disabled={busy} type="submit">{busy?'Please wait…':mode==='login'?'Sign in':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Update password'}</Button></form><div className="auth-links"><Button variant="ghost" disabled={busy} onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setMessage('')}}>{mode==='login'?'First visit? Create account':'Back to sign in'}</Button>{mode==='login'&&<Button variant="ghost" disabled={busy} onClick={()=>{setMode('reset');setError('');setMessage('')}}>Forgot password?</Button>}</div></section></main>
}
