'use client';
import {useCallback,useEffect,useState} from 'react';
import {learningFetch} from '@/lib/supabase/client';
import {ArrowUpRight,ArrowRight,BookOpen,Route,NotebookPen,ChartNoAxesColumnIncreasing,Check,CheckCircle2,ChevronLeft,ChevronRight,Compass,Lightbulb,Target,Download,Settings2,RefreshCw,GraduationCap,Plus,Minus,Equal,Flag,Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {skills,groups,questions,question,evidence,recommended,diagnosticNext,practiceNext,parseAnswer,type Learning,type Question,type Skill} from '@/lib/curriculum';
type Snapshot={state:Learning;revision:number};
type Session={mode:'practice'|'diagnostic'|'review';q:Question;completed:number;correct:number};
type Feedback={correct:boolean;solution:string[];message?:string|null};
const icons=[Plus,Equal,Route,Flag];
function attemptId(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('')}
function Mark(){return <span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 40 40"><path d="M9 28V12l11 13 11-13v16"/></svg></span>}
function Status({value}:{value:string}){return <span className={`status ${value.toLowerCase().replaceAll(' ','-')}`}>{value==='Demonstrated'&&<Check size={12}/>} {value}</span>}
export default function MathBridge(){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('learn'),[lesson,setLesson]=useState<Skill|null>(null),[session,setSession]=useState<Session|null>(null),[answer,setAnswer]=useState(''),[hints,setHints]=useState(0),[feedback,setFeedback]=useState<Feedback|null>(null),[summary,setSummary]=useState<{mode:string;completed:number;correct:number}|null>(null);
 const [settings,setSettings]=useState(false),[name,setName]=useState(''),[goal,setGoal]=useState('Build confidence in algebra'),[showUrdu,setShowUrdu]=useState(false),[inputError,setInputError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const res=await learningFetch('/api/learning',{cache:'no-store'});const data=await res.json() as Snapshot & {error?:string;feedback:Feedback};if(!res.ok)throw Error(data.error||"Unable to load or save progress.");setSnapshot(data);setName(data.state.name);setGoal(data.state.goal);}catch(e){setError(e instanceof Error?e.message:'Could not load progress.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load()},[load]);
 async function mutate(payload:Record<string,unknown>){if(!snapshot)return null;setBusy(true);setError('');try{const res=await learningFetch('/api/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,revision:snapshot.revision})});const data=await res.json() as Snapshot & {error?:string;feedback:Feedback};if(!res.ok)throw Error(data.error||"Unable to load or save progress.");setSnapshot({state:data.state,revision:data.revision});return data;}catch(e){setError(e instanceof Error?e.message:'Your progress could not be saved.');return null;}finally{setBusy(false);}}
 function clearQuestion(){setAnswer('');setHints(0);setFeedback(null);setInputError('')}
 function navigate(value:string){setTab(value);setLesson(null);setSession(null);setSummary(null);clearQuestion()}
 function openLesson(s:Skill){setLesson(s);setSession(null);setSummary(null);setTab('learn');clearQuestion();window.scrollTo({top:0,behavior:'smooth'})}
 function startPractice(s:Skill){if(!snapshot)return;setLesson(null);setSummary(null);setTab('learn');setSession({mode:'practice',q:practiceNext(snapshot.state,s.id),completed:0,correct:0});clearQuestion()}
 async function startDiagnostic(){const data=await mutate({action:'start-diagnostic'});if(data){const q=diagnosticNext(data.state);if(q){setTab('learn');setLesson(null);setSummary(null);setSession({mode:'diagnostic',q,completed:data.state.diagnostic?.seen.length||0,correct:0});clearQuestion();}}}
 async function submit(skip=false){if(!session||busy||feedback)return;if(!skip&&parseAnswer(answer)===null){setInputError('Enter a number, decimal or fraction, such as 5 or 3/4.');return;}
 const data=await mutate({action:'answer',id:attemptId(),qid:session.q.id,answer:skip?'Not sure':answer,hints,mode:session.mode});if(data){setFeedback(data.feedback);setInputError('');}}
 function next(){if(!session||!snapshot||!feedback)return;const completed=session.completed+1,correct=session.correct+(feedback.correct?1:0);const q=session.mode==='diagnostic'?diagnosticNext(snapshot.state):practiceNext(snapshot.state,session.q.skillId);
 if(!q||session.mode==='review'||session.mode==='practice'&&completed>=5){setSummary({mode:session.mode,completed,correct});setSession(null);}else setSession({...session,q,completed,correct});clearQuestion();}
 function retry(q:Question){setTab('learn');setLesson(null);setSummary(null);setSession({q,mode:'review',completed:0,correct:0});clearQuestion()}
 useEffect(()=>{
  const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool||!snapshot)return;const controller=new AbortController();
  const add=(tool:unknown)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}};
  add({name:'read_mathbridge_progress',description:'Read the signed-in learner’s current algebra skill evidence. Does not change learning records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({skills:skills.map(s=>({id:s.id,title:s.title,...evidence(snapshot.state,s.id)})),attempts:snapshot.state.attempts.length})});
  add({name:'open_mathbridge_lesson',description:'Open an algebra lesson in the interface. Does not mark it complete or submit an answer.',inputSchema:{type:'object',properties:{skillId:{type:'string',enum:skills.map(s=>s.id)}},required:['skillId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const id=(input as {skillId?:unknown})?.skillId;const s=skills.find(x=>x.id===id);if(!s)throw Error('Unknown skillId');openLesson(s);return {opened:s.id,title:s.title}}});
  return()=>controller.abort();
 },[snapshot]);
 const state=snapshot?.state;const done=state?skills.filter(s=>evidence(state,s.id).status==='Demonstrated').length:0;const rec=state?recommended(state):skills[0];
 const attempts=state?.attempts||[];const independent=attempts.filter(a=>a.correct&&a.hints===0).length;const mistakes=attempts.filter(a=>!a.correct).filter((a,i,all)=>all.findLastIndex(v=>v.qid===a.qid)===i);
 const pendingMistakes=mistakes.filter(m=>!attempts.some(a=>a.qid===m.qid&&a.created>m.created&&a.correct&&a.hints===0));
 function exportReport(){if(!state)return;const csv=['Skill,Status,Attempts,Correct,Recent independent correct',...skills.map(s=>{const e=evidence(state,s.id);return [s.title,e.status,e.total,e.correct,e.independent].join(',')})].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mathbridge-learning-report.csv';a.click();URL.revokeObjectURL(url);}
 function skillCard(s:Skill){const e=state?evidence(state,s.id):{status:'Not assessed',percent:0};const completed=state?.lessons.includes(s.id);return <button key={s.id} className={'skill-card '+(s.id===rec.id?'recommended':'')} onClick={()=>openLesson(s)}><div className="skill-top"><span className="skill-number">{String(skills.indexOf(s)+1).padStart(2,'0')}</span><Status value={e.status}/></div><h3>{s.title}</h3><p>{s.description}</p><div className="skill-bottom"><span>{completed?'Lesson read':'Lesson + practice'}</span><ArrowUpRight size={18}/></div><Progress value={e.percent} aria-label={`${s.title} evidence`} className="skill-progress"/></button>}
 return <div className="site"><a className="skip" href="#main">Skip to learning</a><header className="header"><a href="/" className="brand" aria-label="MathBridge home"><Mark/><span>math<span className="brand-light">bridge</span></span></a><span className="header-course"><span className="course-dot"/> Algebra foundations</span><div className="header-right"><span className="edition">LEARNING STUDIO</span><Dialog open={settings} onOpenChange={setSettings}><DialogTrigger asChild><Button variant="ghost" className="profile-button" aria-label="Learning settings"><Settings2 size={18}/><span>{state?.name||'Your profile'}</span></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Your learning profile</DialogTitle><DialogDescription>A first name is enough. Your progress is private to your account.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();const d=await mutate({action:'profile',name,goal});if(d)setSettings(false)}} className="profile-form"><label htmlFor="name">First name</label><Input id="name" maxLength={60} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="goal">My goal</label><Select value={goal} onValueChange={setGoal}><SelectTrigger id="goal" className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['Build confidence in algebra','Prepare for school exams','Revisit the foundations'].map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select><Button disabled={busy||!snapshot} type="submit">{busy?'Saving…':'Save profile'}</Button>{error&&<p role="alert" className="error-text">{error}</p>}</form></DialogContent></Dialog></div></header>
 <Tabs value={tab} onValueChange={navigate} className="app-tabs"><div className="navigation"><TabsList className="nav-list" variant="line"><TabsTrigger value="learn"><BookOpen/> Learn</TabsTrigger><TabsTrigger value="map"><Route/> Skill map</TabsTrigger><TabsTrigger value="notebook"><NotebookPen/> Mistake notebook{pendingMistakes.length>0&&<span className="count">{pendingMistakes.length}</span>}</TabsTrigger><TabsTrigger value="report"><ChartNoAxesColumnIncreasing/> Learning report</TabsTrigger></TabsList><span className="nav-meta">YOUR OWN PACE. ONE STEP AT A TIME.</span></div>
 <main id="main" className="main">{error&&<div role="alert" className="error-banner"><span>{error}</span><Button variant="outline" onClick={load} disabled={loading}><RefreshCw size={14}/> Reload progress</Button></div>}
 {loading?<div className="loading"><Loader2 className="spin"/><p>Opening your learning space…</p></div>:<>
 <TabsContent value="learn">
 {session?<div className="study-layout"><div className="study-main"><div className="study-nav"><Button variant="ghost" onClick={()=>navigate('learn')}><ChevronLeft/> Back to my path</Button><span>{session.mode==='diagnostic'?'STARTING-POINT CHECK':session.mode==='review'?'REVISIT A MISTAKE':'FOCUSED PRACTICE'}</span></div><div className="question-panel"><div className="question-meta"><span>{skills.find(s=>s.id===session.q.skillId)?.title}</span><span>{session.mode==='review'?'1 question':`${session.completed+1} / ${session.mode==='diagnostic'?16:5}`}</span></div><Progress value={session.completed/(session.mode==='diagnostic'?16:5)*100} aria-label="Session progress"/><h1>{session.q.prompt}</h1><div className="equation">{session.q.expression}</div><form onSubmit={e=>{e.preventDefault();void submit()}}><label htmlFor="answer">Your answer{session.q.unit?` (${session.q.unit})`:''}</label><div className="answer-row"><Input id="answer" autoComplete="off" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer" disabled={!!feedback||busy} aria-describedby="answer-help"/><Button type="submit" disabled={busy||!!feedback||!snapshot}>{busy?<Loader2 className="spin"/>:'Check answer'}{!busy&&<ArrowRight/>}</Button></div><p id="answer-help" className="muted small">Numbers, decimals and fractions are welcome. For example: −2, 0.5 or 1/2.</p>{inputError&&<p className="error-text" role="alert">{inputError}</p>}</form>
 {!feedback&&<div className="question-actions">{session.mode!=='diagnostic'&&<Button variant="outline" onClick={()=>setHints(h=>Math.min(2,h+1))} disabled={hints>=2||busy}><Lightbulb/> {hints?'Another hint':'Give me a hint'}</Button>}<Button variant="ghost" onClick={()=>submit(true)} disabled={busy||!snapshot}>I’m not sure</Button></div>}
 {hints>0&&!feedback&&<div className="hint-box"><Lightbulb size={20}/><div><strong>A little nudge</strong>{session.q.hint.slice(0,hints).map((h,i)=><p key={i}>{h}</p>)}</div></div>}
 {feedback&&<div className={'feedback '+(feedback.correct?'correct':'incorrect')} role="status"><div className="feedback-heading">{feedback.correct?<CheckCircle2/>:<Lightbulb/>}<h2>{feedback.correct?(hints?'You got it—with a little help.':'That’s right. Nicely done.'):'Let’s work through it.'}</h2></div>{feedback.message&&<p>{feedback.message}</p>}<ol>{feedback.solution.map((s,i)=><li key={i}>{s}</li>)}</ol><Button onClick={next}>{session.mode==='diagnostic'&&state?.diagnostic?.done?'See my learning plan':session.mode==='review'||session.mode==='practice'&&session.completed>=4?'Finish practice':'Next question'}<ArrowRight/></Button></div>}
 </div></div><aside className="study-aside"><span className="eyebrow">A NOTE FOR YOU</span><h2>{session.mode==='diagnostic'?'This is a starting point, not a grade.':'Understanding takes practice.'}</h2><p>{session.mode==='diagnostic'?'Try each question without help. “I’m not sure” is useful too—it helps us choose where to begin.':'Try it independently first. Use a hint when you need one, then revisit a similar problem on your own.'}</p><div className="aside-rule"/><p className="small">Every submitted answer is saved. You can leave and return to your learning plan at any time.</p></aside></div>
 :summary?<section className="summary-panel"><span className="large-check"><CheckCircle2 size={36}/></span><p className="eyebrow">{summary.mode==='diagnostic'?'YOUR STARTING POINT IS READY':'PRACTICE COMPLETE'}</p><h1>{summary.mode==='diagnostic'?'A clearer path forward.':'One step further.'}</h1><p>{summary.mode==='diagnostic'?`You explored all 16 skills. Based on your answers, start with ${rec.title.toLowerCase()}.`:`You answered ${summary.correct} of ${summary.completed} questions correctly in this session.`}</p><div className="recommended-strip"><Compass/><div><strong>{rec.title}</strong><p>{rec.description}</p></div></div><Button onClick={()=>openLesson(rec)}>Continue with this lesson <ArrowRight/></Button><Button variant="ghost" onClick={()=>navigate('map')}>See my skill map</Button><p className="small muted">A starting-point check is a snapshot. Practice gives us more evidence over time.</p></section>
 :lesson?<div className="study-layout"><article className="lesson-panel"><Button variant="ghost" onClick={()=>setLesson(null)}><ChevronLeft/> Back to my path</Button><div className="lesson-title"><span className="eyebrow">LESSON {String(skills.indexOf(lesson)+1).padStart(2,'0')} / ALGEBRA FOUNDATIONS</span><h1>{lesson.title}</h1><p>{lesson.description}</p></div><div className="rule-box"><Lightbulb/><div><h2>The idea</h2><p>{lesson.rule}</p></div></div><div className="worked"><span className="eyebrow">WORKED EXAMPLE</span>{lesson.example.map((step,i)=><div key={i} className="worked-step"><span>{i+1}</span><p>{step}</p></div>)}</div><Button variant="outline" onClick={()=>setShowUrdu(!showUrdu)}>{showUrdu?'Hide Urdu explanation':'Read the key idea in Urdu'} <span lang="ur">اردو</span></Button>{showUrdu&&<p className="urdu" lang="ur" dir="rtl">{lesson.urdu}</p>}<div className="lesson-bottom"><p>Ready to try it yourself?</p><Button disabled={busy||!snapshot} onClick={async()=>{const d=await mutate({action:'lesson',skillId:lesson.id});if(d)startPractice(lesson)}}>Start 5-question practice <ArrowRight/></Button></div></article><aside className="study-aside"><span className="eyebrow">BEFORE THIS LESSON</span><h2>Build on what you know.</h2>{lesson.prerequisites.length?lesson.prerequisites.map(id=>{const s=skills.find(s=>s.id===id)!;return <button className="prereq" key={id} onClick={()=>openLesson(s)}>{s.title}<ChevronRight size={16}/></button>}):<p>This is a foundation skill. You can begin right here.</p>}<div className="aside-rule"/><span className="eyebrow">YOUR EVIDENCE</span><Status value={state?evidence(state,lesson.id).status:'Not assessed'}/><p className="small">Reading a lesson doesn’t count as demonstrating a skill. Independent practice does.</p></aside></div>
 :<><div className="page-heading"><div><p className="eyebrow">YOUR LEARNING SPACE</p><h1>{state?.name?`Welcome back, ${state.name}.`:'A little progress. A stronger foundation.'}</h1><p>Pick up a skill, find your footing, and build from there.</p></div><div className="chapter-label"><span>01</span><div>YOUR COURSE<br/><strong>Algebra foundations</strong></div></div></div>
 <div className="dashboard-top"><section className="focus-card"><div className="focus-copy"><span className="pill"><Compass size={15}/>{state?.diagnostic?.done?'YOUR NEXT STEP':'FIND YOUR STARTING POINT'}</span><h2>{state?.diagnostic?.done?`Let’s work on ${rec.title.toLowerCase()}.`:'Your path starts with what you know.'}</h2><p>{state?.diagnostic?.done?rec.description:'A short check helps us find your strengths and the foundations worth revisiting. No timer. No pressure.'}</p><Button className="white-button" disabled={busy||!snapshot} onClick={()=>state?.diagnostic?.done?openLesson(rec):startDiagnostic()}>{state?.diagnostic?.done?'Open my next lesson':state?.diagnostic?'Continue my check':'Find my starting point'}<ArrowRight size={18}/></Button><span className="focus-meta">{state?.diagnostic?.done?'Guided lesson · 5 practice questions':'16 questions · About 10–15 minutes'}</span></div><div className="math-map" aria-hidden="true"><div className="map-axis vertical"/><div className="map-axis horizontal"/><div className="map-equation">Explore. Practice. Connect.</div><svg viewBox="0 0 250 250"><path d="M34 222 L203 38"/><circle cx="75" cy="177" r="7"/><circle cx="121" cy="128" r="7"/><circle cx="168" cy="77" r="7"/></svg><span className="math-chip">Every step connects.</span></div></section><section className="overview-card"><div className="overview-title"><h2>Your progress</h2><Target size={20}/></div><div className="progress-display"><div className="progress-ring" style={{background:`conic-gradient(#174ae4 ${done/16*360}deg, #e9edf6 0deg)`}}><div><strong>{done}<span>/16</span></strong><small>skills demonstrated</small></div></div></div><div className="overview-stats"><div><strong>{attempts.length}</strong><span>Questions tried</span></div><div><strong>{independent}</strong><span>Independent correct</span></div></div><p className="small muted">Built from your answers, not just lesson completion.</p></section></div>
 <div className="section-heading"><div><span className="eyebrow">THE ROAD AHEAD</span><h2>Your algebra pathway</h2></div><Button variant="ghost" onClick={()=>navigate('map')}>Explore skill map <ArrowUpRight/></Button></div>
 <div className="pathway">{groups.map((g,idx)=>{const Icon=icons[idx];const ss=skills.filter(s=>s.group===idx);const complete=state?ss.filter(s=>evidence(state,s.id).status==='Demonstrated').length:0;return <section className="path-group" key={g}><div className="group-label"><span className={'group-icon group-'+idx}><Icon size={21}/></span><div><p>CHAPTER {String(idx+1).padStart(2,'0')}</p><h3>{g}</h3></div><span className="group-count">{complete}/{ss.length} skills</span></div><div className="skill-grid">{ss.map(skillCard)}</div></section>})}</div></>}
 </TabsContent>
 <TabsContent value="map"><div className="page-heading"><div><p className="eyebrow">SEE THE CONNECTIONS</p><h1>A map, not a race.</h1><p>Each skill builds on earlier ideas. Choose any skill to explore its lesson.</p></div><Button variant="outline" disabled={busy||!snapshot} onClick={startDiagnostic}><Compass/>{state?.diagnostic&&!state.diagnostic.done?'Continue check':'Check my starting point'}</Button></div><div className="map-legend">{['Not assessed','Needs practice','Developing','Demonstrated'].map(s=><Status key={s} value={s}/>)}</div><div className="knowledge-map">{groups.map((g,i)=><section key={g} className="map-column"><div className="map-col-title"><span>0{i+1}</span><h2>{g}</h2></div>{skills.filter(s=>s.group===i).map(s=><button key={s.id} className="map-node" onClick={()=>openLesson(s)}><span className="map-node-title">{s.title}<ArrowUpRight size={17}/></span><Status value={state?evidence(state,s.id).status:'Not assessed'}/><p>{s.prerequisites.length?'Builds on: '+s.prerequisites.map(p=>skills.find(v=>v.id===p)?.title).join(' · '):'Start here · no prerequisites'}</p></button>)}</section>)}</div><div className="info-note"><Lightbulb/><p><strong>What does “demonstrated” mean?</strong> At least four of your last five attempts are correct without hints, across at least three different questions. It is evidence from this practice set, not a formal grade.</p></div></TabsContent>
 <TabsContent value="notebook"><div className="page-heading"><div><p className="eyebrow">MAKE MISTAKES USEFUL</p><h1>Your mistake notebook.</h1><p>Come back, try again, and see what makes sense the second time.</p></div><span className="large-count">{pendingMistakes.length}<small>to revisit</small></span></div>{!mistakes.length?<div className="empty-state"><NotebookPen size={40}/><h2>A fresh page.</h2><p>Questions you miss will appear here, ready for another try.</p><Button onClick={()=>startPractice(rec)} disabled={!snapshot}>Try a practice set <ArrowRight/></Button></div>:<div className="mistake-list">{mistakes.slice().reverse().map(m=>{const q=question(m.qid)!;const resolved=!pendingMistakes.includes(m);return <article className="mistake-card" key={m.id}><div><span className="eyebrow">{skills.find(s=>s.id===q.skillId)?.title}</span><h2>{q.expression}</h2><p>{q.prompt}</p><p className="small muted">Your answer: {m.answer} · {new Date(m.created).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</p></div><div className="mistake-right"><Status value={resolved?'Revisited':'Needs practice'}/><Button variant="outline" onClick={()=>retry(q)}>Try again <ArrowRight/></Button></div></article>})}</div>}</TabsContent>
 <TabsContent value="report"><div className="page-heading"><div><p className="eyebrow">REFLECT & PLAN</p><h1>Your learning report.</h1><p>A clear view of your work, ready to discuss with a teacher.</p></div><Button variant="outline" disabled={!snapshot} onClick={exportReport}><Download/> Export report</Button></div><div className="report-stats"><div><span>Skills demonstrated</span><strong>{done}<small> / 16</small></strong></div><div><span>Independent accuracy</span><strong>{attempts.filter(a=>a.hints===0).length?Math.round(independent/attempts.filter(a=>a.hints===0).length*100)+'%':'—'}</strong></div><div><span>Lessons read</span><strong>{state?.lessons.length||0}</strong></div><div><span>Questions with hints</span><strong>{attempts.filter(a=>a.hints>0).length}</strong></div></div><div className="report-table"><Table><TableHeader><TableRow><TableHead>Skill</TableHead><TableHead>Evidence</TableHead><TableHead>Attempts</TableHead><TableHead>Correct</TableHead><TableHead>Next step</TableHead></TableRow></TableHeader><TableBody>{skills.map(s=>{const e=state?evidence(state,s.id):{status:'Not assessed',total:0,correct:0};return <TableRow key={s.id}><TableCell className="font-medium">{s.title}</TableCell><TableCell><Status value={e.status}/></TableCell><TableCell>{e.total}</TableCell><TableCell>{e.correct}</TableCell><TableCell><Button variant="ghost" onClick={()=>openLesson(s)}>Open lesson <ArrowUpRight/></Button></TableCell></TableRow>})}</TableBody></Table></div><div className="teacher-note"><GraduationCap size={26}/><div><h2>For a conversation with your teacher</h2><p>{pendingMistakes.length?`There are ${pendingMistakes.length} questions to revisit. A useful place to start is ${rec.title.toLowerCase()}.`:'After a few practice sessions, use this report to discuss your next steps together.'} These results reflect this question bank; they are not a standardized assessment.</p></div></div></TabsContent>
 </>}
 </main></Tabs><footer><a className="footer-brand" href="/">mathbridge</a><span>Understand the idea. Build the confidence.</span><span>Algebra foundations · Pilot edition</span></footer></div>
}
